variables:
  PACKAGE_REGISTRY_URL: "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/wimboot"
  PACKAGE_ARCHIVE: "wimboot-$CI_COMMIT_TAG.tar.gz"
  PACKAGE_ARCHIVE_SRC: "wimboot-$CI_COMMIT_TAG.src.tar.gz"

stages:
  - build
  - publish
  - release

build_wimboot:
  stage: build
  image: registry.gitlab.com/multios-usb/builder:202401061637
  tags:
    - saas-linux-medium-amd64
  script: |
    ./build_wimboot.sh
    echo -e "MultiOS-USB wimboot binary files and source code:\n$CI_PROJECT_URL/-/releases/$CI_COMMIT_TAG" > ReadMe.txt
    tar -czf ${PACKAGE_ARCHIVE} ReadMe.txt wimboot.i386.unsigned wimboot.x86_64.unsigned
    mv wimboot.src.tar.gz ${PACKAGE_ARCHIVE_SRC}
  artifacts:
    name: "wimboot_$CI_COMMIT_TAG"
    paths:
      - ${PACKAGE_ARCHIVE}
      - ${PACKAGE_ARCHIVE_SRC}
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+\-\d+$/'

upload_binaries:
  stage: publish
  image: curlimages/curl
  needs:
    - job: build_wimboot
      artifacts: true
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+\-\d+$/'
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file ${PACKAGE_ARCHIVE} ${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/${PACKAGE_ARCHIVE}
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file ${PACKAGE_ARCHIVE_SRC} ${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/${PACKAGE_ARCHIVE_SRC}

release_wimboot:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli
  needs:
    - job: upload_binaries
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+\-\d+$/'
  script:
    - echo "Creating a release for $CI_COMMIT_TAG"
  release:
    name: "MultiOS-USB wimboot $CI_COMMIT_TAG"
    description: 'Changes: $CI_PROJECT_URL/-/commits'
    tag_name: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: '${PACKAGE_ARCHIVE}'
          url: "$PACKAGE_REGISTRY_URL/$CI_COMMIT_TAG/${PACKAGE_ARCHIVE}"
          filepath: '/${PACKAGE_ARCHIVE}'
        - name: '${PACKAGE_ARCHIVE_SRC}'
          url: "$PACKAGE_REGISTRY_URL/$CI_COMMIT_TAG/${PACKAGE_ARCHIVE_SRC}"
          filepath: '/${PACKAGE_ARCHIVE_SRC}'
